amymcgowan/mcc-c4-t2-final-project

README.md
I added the git process to the README.  Formatted it to markdown.  Looks like it should be good to go!
=> Add git process to README

README.md, coding-standards.md
Add version 1 of the coding-standards.md file containing the coding guidelines for our team.
=> Add coding standards

css/food-tips.css, html/food-tips.html
Lays out the content for the first iteration of food-tips page
=> Food tips page

css/main.css, index.html
Add articles and padding.
Generally, I made the layout more nested and flexible like the like food-tips page.
=> Add refinements to layout of home page

html/not-alone.html
This is my first pass at laying out Content A "You Are Not Alone"
=> Lay out Content A not-alone

html/food-tips.html
These changes implement the layout tweaks using Bootstrap that I found late in the day yesterday.
=> Make layout of food-tips more internally consistent

css/main.css, css/reset.css, index.html
Add a reset.css file
Remove unwanted code from index.html and main.css
=> Add reset.css; clean up home page code

html/food-tips.html, html/not-alone.html
Fix hrefs in not-alone.html and food-tips.html navbars
=> Fix an href in navbar

index.html, scripts.js
Layout of elements was in a grid; I changed it to reflect the single column in Figma.
=> Change layout to single column

css/shared.css, index.html
I updated the home page header to match the updated wireframe.  Also changed the container class to container-fluid so that the display spreads from left to right of screen.  Lastly, I started some styling for the header and added color variables.
=> Fix header

css/main.css, css/shared.css, index.html
Added the background color and removed borders in the body.
Changed the font color in the nav.
***sorry this was a long commit, once I got started I got lost.
=> style body for home page

css/not-alone.css, css/shared.css, html/not-alone.html, index.html
Made nav toggle visible on home page
Added styling to not-alone page
=> Style home and not-alone pages

html/food-tips.html, html/not-alone.html, index.html
1. Remove buttons from home page and make the entire width of each white area clickable.
2. Add site name to three pages (in title, navbar and heading if applicable): index.html, not-alone.html, and food-tips.html.
=> Small fixes

css/find-help.css, css/food-tips.css, html/find-help.html, html/food-tips.html
CSS stylings for find-help.html and the nav and header for food-tips.html
=> CSS styling

html/about.html
I created the About HTML page with a contact form using FORMSPREE.
Site name placeholder has been updated to 'Bread Beacon'.
=> Create About HTML page

css/not-alone.css, css/shared.css, html/not-alone.html
Changed header case and added underline
Changed link hovers in nav to white
added FA copywrite
Changed hover effects of cta buttons
=> add icon, changed font size, general tweaks

css/about.css, html/about.html
All the styling for the about .html
=> styling for about.html

index.html
Removed div I was using in index.html to try to create triangle under header
=> Remove triangle div

css/main.css, css/shared.css, html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Fix navbar to top of all pages.
Fix other related display issues.
=> Fix navbar to top of all pages

html/food-tips.html, html/help-others.html
something weird happened to these pages.  Things were doubled.  I fixed it
=> fixed whatever happened to these two pages

html/food-tips.html, html/help-others.html
Reverts amymcgowan/mcc-c4-t2-final-project#36
Trying to see if this PR revert fixes things
=> Revert "fixed whatever happened to these two pages"

css/main.css, css/shared.css, html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Trying to track back to being able to revert 34 after this one...
=> Revert "Fix navbar to top of all pages"

css/about.css, css/food-tips.css, css/help-others.css, css/not-alone.css, css/shared.css, html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html
Reverts amymcgowan/mcc-c4-t2-final-project#34
Undoing this PR: duplicate content and unresolved merge conflicts
=> Revert "Css styling"

css/shared.css, html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Fix navbar to top of viewport on all pages.
In shared.css:
1. Put background color on navbar.
2. Add 3.5rem of padding to top of body.
=> Fix navbar to the top

html/not-alone.html
On not-alone page, reduce the padding between the You Are Heard paragraphs.
=> Reduce spacing between paragraphs

index.html
Use Bootstrap to control width at all screen sizes.
=> Limit width of home page buttons

html/about.html
The hr tag was still on the About pg.  I removed it.  That's all.
=> Remove About pg hr tag

css/find-help.css, css/food-tips.css, css/help-others.css, css/not-alone.css, html/find-help.html, html/food-tips.html, html/help-others.html
Styled the info boxes at the bottom of the page.  Mostly alignments and font-sizes.  Removed borders.
=> Sn bottom page info boxes

html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Copyright info was already in footer and did not need to be updated.
Add padding to top of footer.
=> Add padding to top of footer

html/find-help.html, html/help-others.html, html/not-alone.html
Move the buttons apart so they don't overlap.
=> Fix button scrunching

css/shared.css, html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Added triangles to all of the headers
=> sn - add triangles to headers

html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html
Added descriptive alt text to imgs
=> Amy img a11y

html/about.html
Added 'required' to text that appears in label for email field on form.
Added aria-required attribute to same field.
=> Update a11y for required email field

css/find-help.css, css/main.css, css/not-alone.css, html/find-help.html, html/not-alone.html, index.html
Made the quotes at the bottom of the page blockquotes and made sure they were styled according to the figma.
=> Blockquote

html/find-help.html, html/help-others.html
"b" tags are not in compliance with WCAG.  I replaced them with "strong" tags.
=> Replace <b> tags with <strong>

html/about.html
=> Add autocomplete=on to name and email fields

html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
Add the word Copyright to all footers and aria-hidden=true to all copyright icons
Added aria-hidden=true to all header icons
=> add copyright and aria-hidden to copyright and header icon on all pages

README.md
Added description, links, contact info.
Only thing missing in this current version is the link to the demo video.
=> Amy update readme

README.md
=> Add youtube link

html/about.html, html/find-help.html, html/food-tips.html, html/help-others.html, html/not-alone.html, index.html
There are more pushes coming.  For your convenience, please wait until there is one commit for each page before merging to master.
UPDATE: Ready for merge now
=> Fix the skip nav in index
